language: python
python:
- '3.6'
install: pip install pipenv
stages:
- compile
- test
- deploy
jobs:
  include:
  - stage: compile
    name: Compilation
    script: make devinstall
  - stage: test
    name: Python 2 & Python 3 Compatibility Tests
    script: make full-tox-test
  - stage: test
    name: Bash Tests
    script: make bash-tests
  - stage: test
    name: Zsh Tests
    script: make zsh-tests
  - stage: deploy
    if: type != cron
    name: Deploy to PyPi
    script: echo deploying_placeholder
    deploy:
      provider: pypi
      username: catears
      password:
        secure: "AsS8zMrP5SPJMafIV7AHSrIh4PzA5sj8SZZf8gnAxNVjeTY3mrU1nvLY2jrCIBDh9k+qF7z9fk0uqUAVn0G5aHxShxGL/a6lclQhkZYyKJ06Ip9zUP5jYgR5RWMLEVvSIJm7jdRdOlpJq3cALmpGtrr/BAGb7CFc0IMUWoWLp86FDWdmomqM2UAVh8leZ5y3Ozvpo/ou55C5nI6t76UhRCuDqRzaXcb25W/AuRnjnlhqKjWJP1u8b9IiTp8JUnOdAGXN/hPnHpO6dGRxDOc/1WB4pxB4wERcNI2noeXQiSQoTQkuwKQzUQVnoLbCCxh694lhuPSR0O9wEWmKpPl4TQn3AG3b6BorHLOSJpwslfklBW+Pqe578c35JSoozcxjKvumZSCqJjRqM5TgpDStyGMaKwMC2zKlBM5SUvu0i8VGjE3TLq1KFQmI2hy//TDvNpWWkULo+o2+/HVvim5fWJLmFuCqur26SVlge5YcbUPlBgiAHLrPOLucPEANhspRzCpSAXfut9cwdbUvKXZe0WkMZhfgIt805FtJo8yTUkOhhB5DfIaPFfhrrRHwKcIgLNG9y/xa8imgoPOok2OKtPEfKuBDFSXMWIeO2eycEe1npv7/p41tsrjBZEFqgnnwTiiTJrlWXucHf76he5S0qWmtJsc+lVWsGVlqVeCwB/0="
      on:
        tags: true
  - stage: cron-shell-tests
    name: Live Tests
    if: type = cron
    script: make live-tests
