FROM ubuntu:18.04

WORKDIR /test
RUN apt update && \
    apt install -y python3 python3-pip
COPY ./tests/test_shell.sh /test/
COPY ./dist /test/dist
RUN pip3 install dist/$(ls dist | grep tar.gz)

CMD ["bash", "test_shell.sh"]
